# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
services:
  postgres:
    image: 'postgres'
    ports:
    - '5432:5432'
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: oms_api_test

variables:
  RAILS_ENV: 'test'
  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/oms_api_test'

steps:
  - checkout: self
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '2.7.1'
  - script: |
      gem install bundler
      bundle install
  - script: |
      bin/rails db:create RAILS_ENV=test
      bin/rails db:migrate RAILS_ENV=test
      bin/rails db:seed RAILS_ENV=test
  - script: |
      RAILS_ENV=test rake db:migrate:reset db:seed

  - job: Build_and_Push
    displayName: Image_Build_and_Push
    pool:
      vmImage: ubuntu-latest
    variables:
      tag: '$(Build.BuildId)'
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        containerRegistry: dockerhub
        command: login
        arguments: '-u $(dockerhub_username) -p $(dockerhub_password)'
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: 'azizurehmankhan/postgres-test-app'
        tags: |
          $(tag)
