trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  
pool:
  vmImage: 'ubuntu-latest'
  parallel: 3

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'azizurehmankhan / postgres-test-app'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    
