apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgress-pv
  labels:
    type: local
spec:
  storageClassName: manual
   claimRef:
    name: postgress-pvc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "mnt/data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-pvc
spec:
  storageClassName: manual
  volumeName: postgress-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Mi



